#!/usr/bin/env python3
"""Generate CurveData.h from extracted_components.json."""

import json
import re
from pathlib import Path

INPUT = Path(__file__).resolve().parent.parent / "output" / "extracted_components.json"
OUTPUT = Path(__file__).resolve().parent.parent / "src" / "CurveData.h"

FLOATS_PER_LINE = 12

TYPE_CONFIG = {
    "cab":      ("Cab",      "Cabs"),
    "speaker":  ("Speaker",  "Speakers"),
    "mic":      ("Mic",      "Mics"),
    "position": ("Position", "Positions"),
}


def sanitize_ident(name: str) -> str:
    """Turn a component name into a valid C++ identifier."""
    s = name.replace(" ", "").replace("-", "_")
    if s and s[0].isdigit():
        s = "_" + s
    return re.sub(r"[^A-Za-z0-9_]", "_", s)


def display_name(comp_type: str, name: str) -> str:
    """Short display name for the Curve struct."""
    if comp_type == "cab":
        return re.sub(r"^\d+\s+", "", name)
    return name


TARGET_PEAK_DB = 6.0  # Normalize all curves so peak magnitude = ±6dB at 100% blend


def normalize_curve(mag: list[float]) -> list[float]:
    """Normalize curve so peak absolute value = TARGET_PEAK_DB.
    This ensures all presets have similar impact at the same knob position."""
    import math
    peak = max(abs(v) for v in mag)
    if peak < 0.001:
        return mag  # Don't scale near-zero curves
    scale = TARGET_PEAK_DB / peak
    return [v * scale for v in mag]


def format_float_array(values: list[float]) -> str:
    """Format floats at 4 decimal places, 12 per line."""
    lines = []
    for i in range(0, len(values), FLOATS_PER_LINE):
        chunk = values[i : i + FLOATS_PER_LINE]
        formatted = ", ".join(f"{v:.4f}f" for v in chunk)
        lines.append("    " + formatted)
    return ",\n".join(lines)


def main():
    with open(INPUT) as f:
        data = json.load(f)

    freqs = data["frequencies_hz"]
    components = data["components"]
    num_bins = len(freqs)

    out = []
    out.append("#pragma once")
    out.append("// Auto-generated by generate_curve_header.py — do not edit")
    out.append("#include <array>")
    out.append("")
    out.append("namespace CurveData {")
    out.append("")
    out.append(f"static constexpr int kNumBins = {num_bins};")
    out.append(f"static constexpr std::array<float, kNumBins> kFrequencies = {{")
    out.append(format_float_array(freqs))
    out.append("};")
    out.append("")
    out.append("struct Curve {")
    out.append("    const char* name;")
    out.append("    const float* data;")
    out.append("};")
    out.append("")

    for comp_type in ("cab", "speaker", "mic", "position"):
        if comp_type not in components:
            continue

        singular, plural = TYPE_CONFIG[comp_type]
        items = components[comp_type]
        sorted_names = sorted(items.keys())

        # Individual curve arrays
        # Mics use their natural magnitude (real measured data)
        # Cab/speaker/position are normalized to TARGET_PEAK_DB (extracted residuals)
        for name in sorted_names:
            ident = sanitize_ident(name)
            var_name = f"k{singular}_{ident}"
            mag = items[name]["magnitude_db"]
            raw_peak = max(abs(v) for v in mag)
            if comp_type != "mic":
                mag = normalize_curve(mag)
                norm_peak = max(abs(v) for v in mag)
                print(f"  {name:12s} raw peak {raw_peak:5.2f}dB → normalized {norm_peak:5.2f}dB")
            else:
                print(f"  {name:12s} raw peak {raw_peak:5.2f}dB (natural, no normalization)")
            out.append(f"static constexpr float {var_name}[] = {{")
            out.append(format_float_array(mag))
            out.append("};")
            out.append("")

        # Curve table
        entries = []
        for name in sorted_names:
            ident = sanitize_ident(name)
            var_name = f"k{singular}_{ident}"
            dname = display_name(comp_type, name)
            entries.append(f'    {{"{dname}", {var_name}}}')

        count = len(sorted_names)
        out.append(f"static constexpr Curve k{plural}[] = {{")
        out.append(",\n".join(entries))
        out.append("};")
        out.append(f"static constexpr int kNum{plural} = {count};")
        out.append("")

        print(f"{plural}: {count}")

    out.append("} // namespace CurveData")
    out.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(out))
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
